uname: spotify # change to "spotify" to access Spotify's playlists
playlists:
  - "Today's Top Hits"
  - "All Out 90s"
pl_similarity: .9 # threshold for accepting a playlist name, enter 1 for perfect matches only
show_playlists: true
# Be careful with the following settings
download: false
youtube_dl_path: 'C:\Users\youtube-dl.exe'
output_path: 'C:\Users\me\music'
playlist_folders: true
number_tracks: true
# NOTE: Convert to mp3 requires ffmpeg is installed on your system! Visit http://ffmpeg.org/ for more info
# Windows only for now!
convert_to_mp3 : true